export const sample_users=[
    {
        id:1,
        name:'niggesh',
        email:'niggesh@gmail.com',
        password:'123456',
    },
    {
        id:2,
        name:'biggesh',
        email:'biggesh@gmail.com',
        password:'123456',
    },
    {
        id:3,
        name:'chiggesh',
        email:'chiggesh@gmail.com',
        password:'123456',
    }
]